name: CI

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 16.x

      - name: NPM Install
        run: npm install

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint

  deploy:
    needs: setup
    uses: akhileshns/heroku-deploy@v3.12.14
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: shrouded-escarpment-24419
      heroku_email: danwgross@gmail.com
